apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: "nvmec1"
    image: "kubernetes/pause"
    volumeMounts:
    - mountPath: "/mnt/nvmev1"
      name: "nvmev1"
  volumes:
  - name: "nvmev1"
    nvmeof:
      transport: "rdma"
      traddr: "192.168.55.13"
      trsvcid: 4420
      nqn: "testnqn"
      fsType: "xfs"
      readOnly: false
